import { UI, type Lang } from '../i18n';

export interface QA { q: string; a: string } // `a` is trusted HTML authored here

export const FAQ: Record<Lang, QA[]> = {
  en: [
    { q: 'What is Hourglyph for?',
      a: 'It helps you save Claude Code limits by starting work in off-peak hours. Anthropic has tied limits to the time of day before, peak hours bring more slow replies and failed runs you end up repeating. The <a href="/">heatmap</a> shows when the load peaks in your time zone so you can plan heavy work around it. More tips: <a href="/save-claude-code-limits/">how to save Claude Code limits</a>.' },
    { q: 'When are Claude Code’s peak hours?',
      a: 'Anthropic has described weekdays from 5 to 11 AM Pacific Time (8 AM–2 PM Eastern, 13:00–19:00 UK in summer) as its peak window. That is when US mornings overlap with the European afternoon. The live heatmap on the <a href="/">home page</a> shows how real Claude Code sessions are distributed across the week, converted to your time zone.' },
    { q: 'What is the best time to use Claude Code?',
      a: 'Outside the weekday peak: late evening and night in the Americas, early morning in Europe, and weekends everywhere tend to be calmer. See <a href="/best-time-to-use-claude-code/">best time to use Claude Code</a> for the current quiet windows.' },
    { q: 'Do peak hours affect my Claude Code usage limits?',
      a: 'Not anymore for most paid users. In March 2026 Anthropic made 5-hour session limits drain faster during weekday peak hours. On May 6, 2026 it doubled Claude Code’s 5-hour limits for Pro, Max, Team and seat-based Enterprise plans and removed the peak-hour reduction for Pro and Max. Weekly limits still apply. Details: <a href="/claude-code-usage-limits/">Claude Code usage limits explained</a>.' },
    { q: 'Why does Claude say “overloaded” or feel slow?',
      a: 'An “overloaded” error (HTTP 529) means capacity is temporarily exhausted; it is more likely at peak hours and during incidents. Check <a href="https://status.claude.com" rel="nofollow">status.claude.com</a> for incidents and <a href="/is-claude-slow-right-now/">current load on this site</a>.' },
    { q: 'Is this an official Anthropic tool?',
      a: 'No. Hourglyph is an independent, open-source community project. Numbers come only from people who chose to add the hook or press the check-in button, so they show relative patterns, not Anthropic’s internal traffic.' },
    { q: 'What data does the hook send?',
      a: 'Three kinds of event: a session started, a message was sent (without its text), and a turn finished with four token counts computed locally from your transcript. The server adds the UTC hour, weekday and the country code the network derives from the connection. No prompts, answers, code, paths, session IDs or IP addresses are stored. See <a href="/about/">privacy</a>.' },
    { q: 'Why count messages and tokens, not just sessions?',
      a: 'One session can last all day. Messages show when people are actually working, and tokens show how heavy that work is — together they give a far better picture of load, and of the hours when limits go further.' },
    { q: 'Where does the world map data come from?',
      a: 'From the same check-ins. The country is the two-letter code Cloudflare attaches to each request; only per-day totals per country are published. With a VPN, the VPN’s country is counted.' },
    { q: 'Where does the incident data come from?',
      a: 'From Anthropic’s official status page, status.claude.com, through its public API. Our database syncs recent incidents every hour and counts the hours when an incident affecting Claude, the API or Claude Code was open. Pick “Incidents” above the charts to see when outages cluster.' },
    { q: 'Which time zone is the heatmap in?',
      a: 'Your browser’s time zone. Data is stored in UTC and converted on the fly. There are also dedicated pages for <a href="/peak-hours/">major time zones</a>.' },
    { q: 'Can I use the data?',
      a: 'Yes, it is published under CC BY 4.0 as <a href="/data/">JSON and CSV</a>. Please link back to Hourglyph.' },
  ],
  ru: [
    { q: 'Зачем нужен Hourglyph?',
      a: 'Hourglyph помогает экономить лимиты Claude Code: запускайте работу в ненагруженные часы. Anthropic уже привязывала расход лимитов ко времени суток; в часы пик чаще бывают медленные ответы и сбои, из-за которых задачу приходится перезапускать. <a href="/ru/">Карта</a> показывает, когда нагрузка максимальна в вашем поясе, чтобы планировать тяжёлую работу в обход пика. Другие советы: <a href="/ru/save-claude-code-limits/">как экономить лимиты Claude Code</a>.' },
    { q: 'Когда у Claude Code пиковые часы?',
      a: 'Anthropic называла пиковым окном будни с 5:00 до 11:00 по тихоокеанскому времени — это 15:00–21:00 по Москве с марта по ноябрь и 16:00–22:00 зимой, когда в США действует стандартное время. В это время утро в США совпадает со второй половиной дня в Европе. Живая карта на <a href="/ru/">главной</a> показывает, как распределены реальные сессии Claude Code по неделе в вашем часовом поясе.' },
    { q: 'Когда лучше всего работать в Claude Code?',
      a: 'Вне будничного пика: для России и Европы — утро и первая половина дня, а также поздний вечер и ночь; выходные спокойнее везде. Актуальные спокойные окна — на странице <a href="/ru/best-time-to-use-claude-code/">лучшее время для Claude Code</a>.' },
    { q: 'Влияют ли пиковые часы на лимиты Claude Code?',
      a: 'Для большинства платных пользователей — уже нет. В марте 2026 года Anthropic сделала так, что в будничные пиковые часы 5-часовые лимиты расходовались быстрее. 6 мая 2026 года 5-часовые лимиты Claude Code для Pro, Max, Team и Enterprise (по местам) удвоили, а снижение в пиковые часы для Pro и Max отменили. Недельные лимиты действуют. Подробнее: <a href="/ru/claude-code-usage-limits/">лимиты Claude Code</a>.' },
    { q: 'Почему Claude пишет «overloaded» или тормозит?',
      a: 'Ошибка «overloaded» (HTTP 529) означает, что мощности временно исчерпаны; чаще она бывает в пиковые часы и во время инцидентов. Проверьте <a href="https://status.claude.com" rel="nofollow">status.claude.com</a> и <a href="/ru/is-claude-slow-right-now/">текущую нагрузку</a>.' },
    { q: 'Это официальный инструмент Anthropic?',
      a: 'Нет. Hourglyph — независимый проект сообщества с открытым кодом. Данные поступают только от тех, кто сам подключил hook или нажал кнопку отметки, поэтому карта показывает относительные закономерности, а не внутренний трафик Anthropic.' },
    { q: 'Какие данные отправляет hook?',
      a: 'Три вида событий: началась сессия, отправлено сообщение (без текста) и завершён ход — с четырьмя числами токенов, посчитанными локально по файлу переписки. Сервер добавляет час и день недели по UTC и код страны, который сеть определяет по соединению. Промпты, ответы, код, пути, идентификаторы сессий и IP-адреса не хранятся. Подробнее — в разделе <a href="/ru/about/">о приватности</a>.' },
    { q: 'Зачем считать сообщения и токены, а не только сессии?',
      a: 'Одна сессия может длиться весь день. Сообщения показывают, когда люди действительно работают, а токены — насколько тяжела эта работа. Вместе они дают гораздо более точную картину нагрузки и часов, когда лимиты тратятся экономнее.' },
    { q: 'Откуда данные для карты мира?',
      a: 'Из тех же отметок. Страна — это двухбуквенный код, который Cloudflare добавляет к каждому запросу; публикуются только суммы по странам за день. При работе через VPN учитывается страна VPN-сервера.' },
    { q: 'Откуда данные о сбоях?',
      a: 'С официальной статус-страницы Anthropic, status.claude.com, через её публичный API. База раз в час синхронизирует свежие инциденты и считает часы, когда был открыт инцидент по Claude, API или Claude Code. Выберите «Сбои» над графиками, чтобы увидеть, на какие часы они приходятся.' },
    { q: 'В каком часовом поясе показана карта?',
      a: 'В часовом поясе вашего браузера: данные хранятся в UTC и пересчитываются на лету. Есть и отдельные страницы для <a href="/ru/peak-hours/">популярных часовых поясов</a>, включая Москву, Екатеринбург, Новосибирск и Алматы.' },
    { q: 'Можно ли использовать данные?',
      a: 'Да, они опубликованы под лицензией CC BY 4.0 в формате <a href="/ru/data/">JSON и CSV</a>. Пожалуйста, ставьте ссылку на Hourglyph.' },
  ],
  zh: [
    { q: 'Hourglyph 是做什么的？',
      a: '它帮你把工作安排在非高峰时段，从而节省 Claude Code 额度。Anthropic 曾把额度消耗与时段挂钩；高峰时段响应更慢、失败更多，任务常常要重跑。<a href="/zh/">热力图</a>显示你所在时区的负载高峰，方便你把繁重工作避开高峰。更多技巧：<a href="/zh/save-claude-code-limits/">如何节省 Claude Code 额度</a>。' },
    { q: 'Claude Code 的高峰时段是什么时候？',
      a: 'Anthropic 公布的高峰窗口是工作日太平洋时间 5:00–11:00，即北京时间 20:00–次日 02:00（美国冬令时期间为 21:00–03:00）。这是美国上午与欧洲下午重叠的时段。<a href="/zh/">首页</a>的实时热力图按你的时区显示真实 Claude Code 会话在一周中的分布。' },
    { q: '什么时候使用 Claude Code 最好？',
      a: '避开工作日高峰即可：对中国用户来说，白天和上午通常更空闲；美洲的深夜和欧洲的清晨也较为平静，各地的周末都更空闲。当前的空闲时段见 <a href="/zh/best-time-to-use-claude-code/">Claude Code 最佳使用时间</a>。' },
    { q: '高峰时段会影响我的 Claude Code 用量限制吗？',
      a: '对大多数付费用户来说已经不会了。2026 年 3 月，Anthropic 规定工作日高峰时段 5 小时额度消耗更快。2026 年 5 月 6 日，Pro、Max、Team 和按席位 Enterprise 的 Claude Code 5 小时额度翻倍，Pro 和 Max 的高峰期削减也被取消。每周限制仍然有效。详情：<a href="/zh/claude-code-usage-limits/">Claude Code 用量限制详解</a>。' },
    { q: '为什么 Claude 提示 “overloaded” 或者很慢？',
      a: '“overloaded” 错误（HTTP 529）表示算力暂时耗尽，高峰时段和故障期间更容易出现。可以查看 <a href="https://status.claude.com" rel="nofollow">status.claude.com</a> 上的事件，以及本站的<a href="/zh/is-claude-slow-right-now/">当前负载</a>。' },
    { q: '这是 Anthropic 的官方工具吗？',
      a: '不是。Hourglyph 是一个独立的开源社区项目。数据只来自主动安装 hook 或点击记录按钮的用户，因此它反映的是相对规律，而不是 Anthropic 的内部流量。' },
    { q: 'hook 会发送哪些数据？',
      a: '三类事件：会话开始、发送了一条消息（不含内容），以及一轮结束时在本地根据对话记录算出的四个 token 数。服务器会补充 UTC 小时、星期，以及网络根据连接判断的国家代码。不存储任何提示、回答、代码、路径、会话 ID 或 IP 地址。参见<a href="/zh/about/">隐私说明</a>。' },
    { q: '为什么要统计消息和 token，而不只是会话？',
      a: '一个会话可能持续一整天。消息能反映人们实际在工作的时间，token 能反映工作的繁重程度——两者结合，能更准确地描绘负载，以及哪些时段额度更耐用。' },
    { q: '世界地图的数据从哪里来？',
      a: '来自同样的记录。国家是 Cloudflare 附加在每个请求上的两位字母代码；只公开按国家的每日汇总。使用 VPN 时，计入的是 VPN 所在的国家。' },
    { q: '故障数据从哪里来？',
      a: '来自 Anthropic 官方状态页 status.claude.com 的公开 API。我们的数据库每小时同步一次最新事件，并统计 Claude、API 或 Claude Code 存在未关闭事件的小时数。在图表上方选择“故障”，即可看到故障集中在哪些时段。' },
    { q: '热力图用的是哪个时区？',
      a: '你浏览器的时区。数据以 UTC 存储并实时换算。另外还有<a href="/zh/peak-hours/">主要时区</a>的专门页面，包括北京时间、日本时间和新加坡时间。' },
    { q: '我可以使用这些数据吗？',
      a: '可以，数据以 CC BY 4.0 许可发布，提供 <a href="/zh/data/">JSON 和 CSV</a> 格式。请注明来源并链接到 Hourglyph。' },
  ],
  ja: [
    { q: 'Hourglyph は何のためのツールですか？',
      a: '空いている時間に作業を始めることで、Claude Code の利用上限を節約するためのツールです。Anthropic は以前、上限の消費を時間帯と結びつけたことがあります。ピーク時間は応答が遅く失敗も多いため、やり直しが増えます。<a href="/ja/">ヒートマップ</a>を見れば、あなたのタイムゾーンで負荷がピークになる時間がわかり、重い作業をずらせます。ほかのコツ：<a href="/ja/save-claude-code-limits/">Claude Code の利用上限を節約する方法</a>。' },
    { q: 'Claude Code のピーク時間はいつですか？',
      a: 'Anthropic はピーク時間として平日の太平洋時間 5:00〜11:00 を示しています。日本時間では 21:00〜翌 03:00（米国の冬時間中は 22:00〜翌 04:00）です。米国の午前とヨーロッパの午後が重なる時間帯です。<a href="/ja/">トップページ</a>のライブヒートマップでは、実際の Claude Code セッションの1週間の分布をあなたのタイムゾーンで確認できます。' },
    { q: 'Claude Code を使うのに最適な時間は？',
      a: '平日のピークを避けることです。日本では日中から夕方にかけてが比較的空いており、米国の深夜やヨーロッパの早朝も落ち着いています。週末はどの地域でも空いています。現在の空いている時間帯は <a href="/ja/best-time-to-use-claude-code/">Claude Code を使うおすすめの時間</a> をご覧ください。' },
    { q: 'ピーク時間は Claude Code の利用上限に影響しますか？',
      a: 'ほとんどの有料ユーザーにとって、今は影響しません。2026年3月、Anthropic は平日のピーク時間に5時間上限の消費が早まるようにしました。2026年5月6日には、Pro・Max・Team・シート制 Enterprise の Claude Code の5時間上限を2倍にし、Pro と Max のピーク時の削減を廃止しました。週間上限は引き続き適用されます。詳細：<a href="/ja/claude-code-usage-limits/">Claude Code の利用上限の解説</a>。' },
    { q: 'Claude が「overloaded」と表示したり、遅くなったりするのはなぜ？',
      a: '「overloaded」エラー（HTTP 529）は、処理能力が一時的に不足していることを意味します。ピーク時間や障害発生中に起きやすくなります。障害は <a href="https://status.claude.com" rel="nofollow">status.claude.com</a> で、負荷は<a href="/ja/is-claude-slow-right-now/">このサイトの現在の負荷</a>で確認できます。' },
    { q: 'これは Anthropic の公式ツールですか？',
      a: 'いいえ。Hourglyph は独立したオープンソースのコミュニティプロジェクトです。データは hook を追加したり記録ボタンを押したりした人からのみ集まるため、表示されるのは相対的な傾向であり、Anthropic の内部トラフィックではありません。' },
    { q: 'hook はどんなデータを送信しますか？',
      a: '3種類のイベントです：セッションの開始、メッセージの送信（本文は含みません）、そしてターンの終了時に会話ログからローカルで計算した4つのトークン数。サーバー側で UTC の時間と曜日、接続元からネットワークが判定した国コードを付け加えます。プロンプト、回答、コード、パス、セッション ID、IP アドレスは保存しません。詳しくは<a href="/ja/about/">プライバシー</a>をご覧ください。' },
    { q: 'なぜセッションだけでなく、メッセージとトークンも数えるのですか？',
      a: '1つのセッションが丸1日続くこともあるからです。メッセージは実際に作業している時間を、トークンはその作業の重さを示します。両方を合わせることで、負荷の様子や上限が長持ちする時間帯をより正確に把握できます。' },
    { q: '世界地図のデータはどこから来ていますか？',
      a: '同じ記録からです。国は Cloudflare が各リクエストに付ける2文字のコードで、公開するのは国ごとの日別合計だけです。VPN を使っている場合は VPN の国として数えられます。' },
    { q: '障害のデータはどこから来ていますか？',
      a: 'Anthropic の公式ステータスページ status.claude.com の公開 API からです。データベースが1時間ごとに最新の障害を同期し、Claude・API・Claude Code の障害が発生中だった時間を数えます。グラフの上で「障害」を選ぶと、障害が集中する時間帯がわかります。' },
    { q: 'ヒートマップはどのタイムゾーンで表示されますか？',
      a: 'お使いのブラウザのタイムゾーンです。データは UTC で保存し、表示時に換算しています。日本時間、韓国時間、中国時間など<a href="/ja/peak-hours/">主なタイムゾーン</a>の専用ページもあります。' },
    { q: 'データを利用してもいいですか？',
      a: 'はい。CC BY 4.0 ライセンスで <a href="/ja/data/">JSON と CSV</a> として公開しています。Hourglyph へのリンクを添えてください。' },
  ],
};

const strip = (html: string) => html.replace(/<[^>]+>/g, '');

export const faqJsonLd = (lang: Lang) => ({
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  inLanguage: UI[lang].htmlLang,
  mainEntity: FAQ[lang].map(({ q, a }) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: strip(a) } })),
});
